import BASE_URL from "../BASE_URL";
const GET_EVENT_PARTICIPATIONS = BASE_URL + "/participations/event/";
const SET_ATTENDANCE = BASE_URL + "/participations/";
const PARTICIPATE = BASE_URL + "/participations"
const GET_HIKER_PARTICIPATIONS = BASE_URL + "/events/hiker/"
export{GET_EVENT_PARTICIPATIONS,SET_ATTENDANCE,PARTICIPATE,GET_HIKER_PARTICIPATIONS}